// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEsiv8ZJPIsA6PyPtAj0j5uYOgafXDe8g',
    appId: '1:854124708286:web:fc9a970e3a96a2df66b9ef',
    messagingSenderId: '854124708286',
    projectId: 'creepsupport2',
    authDomain: 'creepsupport2.firebaseapp.com',
    storageBucket: 'creepsupport2.appspot.com',
    measurementId: 'G-RM31Y89MMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1alvlYv65LZ3ihBczgKzhvT0oSKuBAe0',
    appId: '1:854124708286:android:961d9b3353226b6c66b9ef',
    messagingSenderId: '854124708286',
    projectId: 'creepsupport2',
    storageBucket: 'creepsupport2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsEXdV44NPTBJBwiv8nuHpdNK5PltQiWY',
    appId: '1:854124708286:ios:c94324dc2651c8fa66b9ef',
    messagingSenderId: '854124708286',
    projectId: 'creepsupport2',
    storageBucket: 'creepsupport2.appspot.com',
    iosClientId: '854124708286-2i1as3t4qpb6pp7urce95pdlp1p15ra4.apps.googleusercontent.com',
    iosBundleId: 'com.aimbesi1.creepsupport2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsEXdV44NPTBJBwiv8nuHpdNK5PltQiWY',
    appId: '1:854124708286:ios:c94324dc2651c8fa66b9ef',
    messagingSenderId: '854124708286',
    projectId: 'creepsupport2',
    storageBucket: 'creepsupport2.appspot.com',
    iosClientId: '854124708286-2i1as3t4qpb6pp7urce95pdlp1p15ra4.apps.googleusercontent.com',
    iosBundleId: 'com.aimbesi1.creepsupport2',
  );
}
